//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CustomerCode { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string WorkingArea { get; set; }
        public string Country { get; set; }
        public Nullable<int> Grade { get; set; }
        public decimal OpeningAmount { get; set; }
        public decimal ReceivedAmount { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal OutstandingAmount { get; set; }
        public string PhoneNumber { get; set; }
        public string AgentCode { get; set; }
    }
}
