//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public decimal OrderNumber { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal AdvanceAmount { get; set; }
        public System.DateTime Date { get; set; }
        public string CustomerCode { get; set; }
        public string AgentCode { get; set; }
        public string Description { get; set; }
    }
}
