//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssignmentEntities : DbContext
    {
        public AssignmentEntities()
            : base("name=AssignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<CustomerTable> CustomerTables { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual ObjectResult<usp_GetAgentDetails_Result> usp_GetAgentDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAgentDetails_Result>("usp_GetAgentDetails");
        }
    
        public virtual ObjectResult<usp_GetCustomerDetails_Result> usp_GetCustomerDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCustomerDetails_Result>("usp_GetCustomerDetails");
        }
    
        public virtual ObjectResult<usp_GetOrderCount_Result> usp_GetOrderCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderCount_Result>("usp_GetOrderCount");
        }
    
        public virtual ObjectResult<usp_GetOrderDetailsByAgentId_Result> usp_GetOrderDetailsByAgentId(string aCode)
        {
            var aCodeParameter = aCode != null ?
                new ObjectParameter("ACode", aCode) :
                new ObjectParameter("ACode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderDetailsByAgentId_Result>("usp_GetOrderDetailsByAgentId", aCodeParameter);
        }
    
        public virtual ObjectResult<usp_GetOrderDetailsOnANameCName_Result> usp_GetOrderDetailsOnANameCName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderDetailsOnANameCName_Result>("usp_GetOrderDetailsOnANameCName");
        }
    }
}
